CREATE BUFFERPOOL tempspace2pool SIZE 500 PAGESIZE 32K
CREATE TEMPORARY TABLESPACE TEMPSPACE2 PAGESIZE 32K MANAGED BY DATABASE USING(FILE '/tmp/DB2/TEMPSPACE2.TBS' 20M) BUFFERPOOL tempspace2pool
ALTER TABLESPACE TEMPSPACE2 AUTORESIZE YES