FROM opentext/vertica-ce:25.2.0-0

COPY ./docker-entrypoint.sh /home/dbadmin/docker-entrypoint.sh

#RUN chmod +x /home/dbadmin/docker-entrypoint.sh

#ENTRYPOINT ["/opt/vertica/bin/docker-entrypoint.sh"]
#EXPOSE 5433