CREATE DATABASE IF NOT EXISTS test_ssl;
CREATE USER 'test_ssl'@'%' IDENTIFIED BY 'test_ssl' REQUIRE SSL;
GRANT ALL ON test_ssl.* TO 'test_ssl'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS test_x509;
CREATE USER 'test_x509'@'%' IDENTIFIED BY 'test_x509' REQUIRE x509;
GRANT ALL ON test_x509.* TO 'test_x509'@'%';
FLUSH PRIVILEGES;

GRANT CREATE USER ON *.* TO 'guest';
GRANT SELECT ON mysql.* TO 'guest';
FLUSH PRIVILEGES;

-- ALTER INSTANCE RELOAD TLS;