version: '2.1'

services:
    greenplum_6.1:
      container_name: greenplum_6.1
      ports:
        - "54304:5432"
      image: datagrip/greenplum:6.1
      privileged: true
      hostname: greenplum_6.1.0
      security_opt:
       - seccomp:unconfined
      healthcheck:
        test: grep -r -i --include \*.log "Database successfully started" || exit 1
